"""Generate docs/ROSTER.md tables from data/creatures/*.json."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
ORDER = ["giant_ape","fire_reptile","flying_dragon","giant_robot","giant_skeleton","diaper_baby","army_of_ten","pointy_hat_wizard","blob","giant_mantis","stone_colossus","eyeball_beast","giant_tarantula","dark_knight_rider","shadow_flame_demon","giant_anaconda"]
LOCO = {"biped":"2-leg IK gait","multi":"multi-limb IK gait","serpent":"serpentine trail-follow","swarm":"10 independent unit walkers"}
out = ["# Tournament roster (16 entrants)\n", "Generated by `tools/roster/make_roster_doc.py` from `data/creatures/*.json`. Every entrant is exactly 1,000 cubes.\n",
       "| # | Entrant | Rig | Ranged | Attacks | Cube allocation (region: cubes) | Unfair advantage / sacrifice |", "|---|---|---|---|---|---|---|"]
for n, i in enumerate(ORDER, 1):
    d = json.load(open(ROOT/"data/creatures"/f"{i}.json"))
    assert len(d["cells"]) == 1000
    groups = {}
    for e in d["cells"]: groups[e["major"]] = groups.get(e["major"], 0) + 1
    alloc = ", ".join(f"{k} {v}" for k, v in sorted(groups.items(), key=lambda kv: -kv[1]))
    ranged = [a["label"] for a in d["attacks"].values() if "ranged" in a]
    attacks = ", ".join(a["label"].title() for a in d["attacks"].values() if "ranged" not in a)
    out.append(f"| {n} | {d['name'].title()} | {LOCO[d.get('rig_type','biped')]} | {', '.join(x.title() for x in ranged) or '—'} | {attacks} | {alloc} | {d.get('notes','')} |")
(ROOT/"docs/ROSTER.md").write_text("\n".join(out)+"\n", encoding="utf-8")
print("\n".join(out))
